### PR TITLE
add tutorial and exmaple for building dynamic tables

### PR DESCRIPTION
**Pull request by iw4p**
Add a simple and new dynamic table example code and PDF inside the tutorial directory. 👻

### CODE REVIEW

**Comment by Lucas-C** [comment]
Thank you for submitting this contribution @iw4p !

Could you please explain why your script should be included in `fpdf2`?
What does it bring more than the current [documentation page](https://pyfpdf.github.io/fpdf2/Tables.html)?
And wouldn't it be more interesting to expand the documentation instead of introducing a standalone script with no references nor explanations?

In the past we suggested that users implement [their own `table()` method in subclasses](https://github.com/PyFPDF/fpdf2/issues/173#issuecomment-868470540).
I'm totally open to adding more examples or explanations on how to produce tables,
I'd just would like to understand what does your PR bring new 😊

**Comment by iw4p** [comment]
Hello dear Lucas,
Your welcome.
As a habit, I always first check the examples and tutorials to find the best example, So I checked the tutorials directory and wrote my code, so I decided to push it inside tutorial examples for tables example, maybe also someone needs it too and use it without reading the full doc.
I read the doc for learning how `.cell` works, but not enough carefully to see the **Tables** section.

**Comment by Lucas-C** [comment]
Thanks for the explanation on your motivation @iw4p

I still don't see why this script should be included,
given we already have an example that generates a table in `tutorial/`: [tuto5.py](https://github.com/PyFPDF/fpdf2/blob/master/tutorial/tuto5.py)

I hope you won't mind if I don't merge your PR as it is.
If you'd really like to make a contribution, maybe consider improving the current scripts & documentation, or look at [an existing issue](https://github.com/PyFPDF/fpdf2/labels/good%20first%20issue)

**Comment by iw4p** [comment]
Oh, I see, I just tried to add another example, maybe it's useful for someone.
There's no problem if it's not necessary to be inside the tutorials directory or PR's not accepted, I understood.
And again, thanks for your suggestion, I'll try to contribute something more useful next time. :D

**Pull request closed without merging**
