### PR TITLE
WIP: multi-line cells in table

### PR DESCRIPTION
**Pull request by RubendeBruin**
This is the implementation for #91 
Conflicts with #211 (was not aware of this)

the idea of this implementation is to separate the creation of the table from the HTML parser.
The HTML parser will create a Table object when a `<table>` tag is encountered. Following `<td>`, `<tr>` and `` tags as well as data is then passed to the Table object.
The table is only processed when `</table>` is encountered. At that time all the table contents are known and the cell sizes can be determined. 

Good:
- Table object can also be used outside html

Issues:
- multi_cell does not support text formatting, so formatting of text inside a cell can not be handled.
- mixed image/text cells. 

It would be great if there was a function like multi_cell that could handle HTML. In that case it would be a matter of passing all the html between `<td>` tags to that function.

### CODE REVIEW

**Comment by Lucas-C** [comment]
I like the approach overall!

Writing a dedicated module really seems a good idea to me 👍
Could you however name it `html_table`; or create a `fpdf/html/` subdirectory?

> It would be great if there was a function like multi_cell that could handle HTML
You may need to write one as part of this feature...

I haven't reviewed the code yet, I'll wait for the PR not be in WIP, or for you to request a code review 😉

**Comment by Lucas-C** [comment]
Just a quick notice: if you plan to continue working on this, you will need to rebase your branch 😉

**Comment by RubendeBruin** [comment]
Hi @Lucas-C , I'm struggling a bit with implementing this. With my proposed implementation we will loose some of the current functionality as the data in the cells needs to be supported by `multi_cell`. For this to work we'd need a function that can parse html with a set output width and return the output height.

**Comment by Lucas-C** [comment]
> we'd need a function that can parse html with a set output width and return the output height

OK. I think think could be built from using `fpdf.html.HTML2FPDF`,
that process HTML `<table>` tags with a fixed `width`,
and then retrieve the resulting difference in `.y` position.
Also, maybe `multi_cell(..., split_only=True)` could be of some use.

**Comment by RubendeBruin** [comment]
would it be an idea to:
- create a new temporary pdf document 
- set the .w to the width of the column
- run fpdf.html.HTML2FPDF on the code in the cell
- retrieve .y 
- delete the temporary pdf document

**Comment by RubendeBruin** [comment]
forcing output into width of a column:

```pyhton
y0 = pdf.get_y()
pdf.set_left_margin(60)
column_width = 20
pdf.set_right_margin(pdf.w - pdf.l_margin - column_width)
pdf.write_html(html)

# another column
pdf.set_y(y0)
pdf.set_left_margin(80)   
column_width = 20
pdf.set_right_margin(pdf.w - pdf.l_margin - column_width)
pdf.write_html(html)
```

**Comment by RubendeBruin** [comment]
Should we keep allow breaking pages in a row?
If not: before each cell, check all cells in the row to see if any would overflow the page (unbreakable)

**Comment by Lucas-C** [comment]
You 2nd suggestion sounds like the best:
if a page break occurs, it should bring the whole row onto the next page.

**Comment by Lucas-C** [comment]
Hi @RubendeBruin 

Would you like to continue working on this?
It's ok if you moved to other matters 😊

**Comment by RubendeBruin** [comment]
Hi @Lucas-C ,
yes, I'm still planning to pick this up. However my planning for the coming months is such that it will not happen soon.
The scope is a bit more elaborate than I had hoped. If there is somebody else who wants to work on this then please go ahead - if not then I will continue on this in due time.

**Comment by Lucas-C** [comment]
> yes, I'm still planning to pick this up. However my planning for the coming months is such that it will not happen soon.
> The scope is a bit more elaborate than I had hoped. If there is somebody else who wants to work on this then please go ahead - if not then I will continue on this in due time.

Hi @RubendeBruin
This PR has been open for a year.
Unless you plan to work on this in the immediate future, I suggest that we close it.
Anyone will be welcome to open a another PR to implement this.

**Pull request closed without merging**
