### PR TITLE
Rename docs/pygal_chart_cairo.PNG -> png. Closes #835.

### LINKED ISSUE #835: Pre-commit hooks failed on `docs/pygal_chart_cairo.PNG`
fpdf2 – master.
system: Linux Debian Bookworm

I can not commit anything, because line-ends are changed in PNG file!

I guess file `docs/pygal_chart_cairo.PNG` gas wrong extension. Another files (`*.png`) is OK.
```
$ git diff docs/pygal_chart_cairo.PNG
warning: in the working copy of 'docs/pygal_chart_cairo.PNG', CRLF will be replaced by LF the next time Git touches it
diff --git a/docs/pygal_chart_cairo.PNG b/docs/pygal_chart_cairo.PNG
index 1a044d87..17ce86fe 100644
Binary files a/docs/pygal_chart_cairo.PNG and b/docs/pygal_chart_cairo.PNG differ
```

Of course I've installed pre-commit hooks.

Can I rename this file `docs/pygal_chart_cairo.PNG` → `docs/pygal_chart_cairo.png`?

### PR DESCRIPTION
**Pull request by rysson**
The git hooks replace CRLF  by LF in PNG file!

I've just renamed PNG to png:
```bash
git mv docs/pygal_chart_cairo.PNG docs/pygal_chart_cairo.png
```

and I updated link in `docs/SVG.md`.

 

**Checklist**:

- [x] The GitHub pipeline is OK (green), 
      meaning that both `pylint` (static code analyzer) and `black` (code formatter) are happy with the changes of this PR.

- [ ] A unit test is covering the code added / modified by this PR – no, there is no code

- [x] This PR is ready to be merged 

- [ ] In case of a new feature, docstrings have been added, with also some documentation in the `docs/` folder

- [ ] A mention of the change is present in `CHANGELOG.md`

By submitting this pull request, I confirm that my contribution is made under the terms of the [GNU LGPL 3.0 license](https://github.com/PyFPDF/fpdf2/blob/master/LICENSE).

### CODE REVIEW

**Review by Lucas-C — APPROVED** [review]

**Comment by Lucas-C** [comment]
Hi @rysson

Thank you for the contribution.

I just fixed an issue with Pylint on the `master` branch that caused the GitHub Actions pipeline to break.
Could you please your branch on `master` so that it includes this fix, and the pipeline shoud then pass?
I cannot do it myself as you did not allow edits from maintainers on your branch: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by Lucas-C** [comment]
Could you please rebase one more time?

I have just solved another issue with a PDF checker we use: #841

**Comment by rysson** [comment]
Ok. It was a little creepy, because `git checkout . ` made modified files. I couldn't modify `.gitattribute`. Add locally `docs/.gitattributes` helped get clean master branch. Of course `docs/.gitattributes` it not commited.

Could you check if it's ok now?

**Comment by Lucas-C** [comment]
Merged!

Thank you again @rysson 😊

**Pull request merged**
