### PR TITLE
fix zero height ln() after empty cell(), #601

### LINKED ISSUE #601: fpdf.ln() not working in version 2.5.7 if last fpdf.cell() was called with empty txt
In the following example line feed should use as height the height value of the last printed cell, which is the height of the current font size. This works in fpdf2 version 2.5.6, but no longer in version 2.5.7. In version 2.5.7 the used height value is 0. 

**Minimal code**
```python
from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.set_font("Times", size=12)

for i in range(1, 10):
    pdf.cell(w=100, h=None, txt=f"Printing line number {i}")
    pdf.cell(w=100, h=None, txt="")
    pdf.ln()

pdf.output("test.pdf") 
```

**Environment**
* OS Linux
* Python version 3.10
* fpdf2 version 2.5.7

[test_2.5.6.pdf](https://github.com/PyFPDF/fpdf2/files/9995186/test_2.5.6.pdf)
[test_2.5.7.pdf](https://github.com/PyFPDF/fpdf2/files/9995188/test_2.5.7.pdf)

### PR DESCRIPTION
**Pull request by gmischler**
e.g. Fixes #601 

**Checklist**:

- [x] The GitHub pipeline is OK (green), 
      meaning that both `pylint` (static code analyzer) and `black` (code formatter) are happy with the changes of this PR.
- [x] A unit test is covering the code added / modified by this PR
- [x] This PR is ready to be merged 
- [NA] In case of a new feature, docstrings have been added, with also some documentation in the `docs/` folder
- [x] A mention of the change is present in `CHANGELOG.md`

By submitting this pull request, I confirm that my contribution is made under the terms of the [GNU LGPL 3.0 license](https://github.com/PyFPDF/fpdf2/blob/master/LICENSE).

### CODE REVIEW

**Comment by gmischler** [comment]
@Lucas-C, looks like you'll have to increase memory allowance for the Windows testing instances.

**Comment by Lucas-C** [comment]
> @Lucas-C, looks like you'll have to increase memory allowance for the Windows testing instances.

I have just done that in #603, could you rebase your PR please?

**Comment by gmischler** [comment]
> I have just done that in #603...

Not quite there yet.

**Comment by Lucas-C** [comment]
Strange, the GitHub Actions pipeline is passing on the `master` branch:
https://github.com/PyFPDF/fpdf2/actions?query=branch%3Amaster

**Comment by gmischler** [comment]
> Strange, the GitHub Actions pipeline is passing on the `master` branch:

The exact memory used on each run appears to be a bit random, with a different instance going over the limit each time it fails. So probably best to just allow for a somewhat generous limit to get some more wiggle room.

**Comment by Lucas-C** [comment]
Could it be that the memory usage increases along with the tests count?
The memory limit was originally set to 125mb:
https://github.com/PyFPDF/fpdf2/blob/7fce7231547060555fadb7bbeb05ef97d6dc8f4b/test/image/test_load_image.py#L45

You can bump the limit passed to `memunit.assert_lt_mb()` in `test/image/test_load_image.py` as part of your PR, maybe to 140mb?

**Comment by Lucas-C** [comment]
Merged! Thank you @gmischler

**Pull request merged**
