### PR TITLE
New alt_text parameter for FPDF.image & new structure_tree module

### PR DESCRIPTION
**Pull request by Lucas-C**
I had to implemented PDF objects as classes in the new `structure_tree` module,
but I wonder if we should not add [pdfrw](https://github.com/pmaupin/pdfrw) as a dependency and reuse its great, clean implementation of those objects instead...

### CODE REVIEW

**Comment by Lucas-C** [comment]
Warnings raised by `qpdf`:
```
checking ./test/image/alt_text/image_alt_text.pdf
WARNING: ./test/image/alt_text/image_alt_text.pdf (object 12 0, offset 4822): unknown token while reading object; treating as string
WARNING: ./test/image/alt_text/image_alt_text.pdf (object 12 0, offset 4864): unknown token while reading object; treating as string
WARNING: ./test/image/alt_text/image_alt_text.pdf (object 12 0, offset 4762): expected dictionary key but found non-name object; inserting key /QPDFFake1
WARNING: ./test/image/alt_text/image_alt_text.pdf (object 12 0, offset 4762): expected dictionary key but found non-name object; inserting key /QPDFFake2
WARNING: ./test/image/alt_text/image_alt_text.pdf (object 9 0, offset 4516): unknown token while reading object; treating as string
WARNING: ./test/image/alt_text/image_alt_text.pdf (object 9 0, offset 4515): expected dictionary key but found non-name object; inserting key /QPDFFake1
WARNING: ./test/image/alt_text/image_alt_text.pdf (object 9 0, offset 4515): expected dictionary key but found non-name object; inserting key /QPDFFake2
WARNING: ./test/image/alt_text/image_alt_text.pdf (object 8 0, offset 4465): unknown token while reading object; treating as string
WARNING: ./test/image/alt_text/image_alt_text.pdf (object 10 0, offset 4575): unknown token while reading object; treating as string
WARNING: ./test/image/alt_text/image_alt_text.pdf (object 5 0, offset 531): expected endobj

checking ./test/image/alt_text/same_alt_text_for_image_repeated.pdf
WARNING: ./test/image/alt_text/same_alt_text_for_image_repeated.pdf (object 12 0, offset 4828): unknown token while reading object; treating as string
WARNING: ./test/image/alt_text/same_alt_text_for_image_repeated.pdf (object 12 0, offset 4870): unknown token while reading object; treating as string
WARNING: ./test/image/alt_text/same_alt_text_for_image_repeated.pdf (object 12 0, offset 4768): expected dictionary key but found non-name object; inserting key /QPDFFake1
WARNING: ./test/image/alt_text/same_alt_text_for_image_repeated.pdf (object 12 0, offset 4768): expected dictionary key but found non-name object; inserting key /QPDFFake2
WARNING: ./test/image/alt_text/same_alt_text_for_image_repeated.pdf (object 9 0, offset 4522): unknown token while reading object; treating as string
WARNING: ./test/image/alt_text/same_alt_text_for_image_repeated.pdf (object 9 0, offset 4521): expected dictionary key but found non-name object; inserting key /QPDFFake1
WARNING: ./test/image/alt_text/same_alt_text_for_image_repeated.pdf (object 9 0, offset 4521): expected dictionary key but found non-name object; inserting key /QPDFFake2
WARNING: ./test/image/alt_text/same_alt_text_for_image_repeated.pdf (object 8 0, offset 4471): unknown token while reading object; treating as string
WARNING: ./test/image/alt_text/same_alt_text_for_image_repeated.pdf (object 10 0, offset 4581): unknown token while reading object; treating as string
WARNING: ./test/image/alt_text/same_alt_text_for_image_repeated.pdf (object 5 0, offset 537): expected endobj

checking ./test/image/alt_text/same_alt_text_for_image_repeated_on_different_pages.pdf
WARNING: ./test/image/alt_text/same_alt_text_for_image_repeated_on_different_pages.pdf (object 14 0, offset 5039): unknown token while reading object; treating as string
WARNING: ./test/image/alt_text/same_alt_text_for_image_repeated_on_different_pages.pdf (object 14 0, offset 5081): unknown token while reading object; treating as string
WARNING: ./test/image/alt_text/same_alt_text_for_image_repeated_on_different_pages.pdf (object 14 0, offset 4979): expected dictionary key but found non-name object; inserting key /QPDFFake1
WARNING: ./test/image/alt_text/same_alt_text_for_image_repeated_on_different_pages.pdf (object 14 0, offset 4979): expected dictionary key but found non-name object; inserting key /QPDFFake2
WARNING: ./test/image/alt_text/same_alt_text_for_image_repeated_on_different_pages.pdf (object 11 0, offset 4732): unknown token while reading object; treating as string
WARNING: ./test/image/alt_text/same_alt_text_for_image_repeated_on_different_pages.pdf (object 11 0, offset 4731): expected dictionary key but found non-name object; inserting key /QPDFFake1
WARNING: ./test/image/alt_text/same_alt_text_for_image_repeated_on_different_pages.pdf (object 11 0, offset 4731): expected dictionary key but found non-name object; inserting key /QPDFFake2
WARNING: ./test/image/alt_text/same_alt_text_for_image_repeated_on_different_pages.pdf (object 10 0, offset 4680): unknown token while reading object; treating as string
WARNING: ./test/image/alt_text/same_alt_text_for_image_repeated_on_different_pages.pdf (object 12 0, offset 4791): unknown token while reading object; treating as string
WARNING: ./test/image/alt_text/same_alt_text_for_image_repeated_on_different_pages.pdf (object 7 0, offset 743): expected endobj
```

**Comment by Lucas-C** [comment]
All 3 PDF checkers validate the new samples ! Looks good :)

**Comment by alexp1917** [comment]
is it possible to either make the `self.Type` follow an inheritance contract? or maybe an explanation of why not in the docstring... this is very exciting.

I feel like i have to review it a couple more times for the code to be readable. (its for that reason i added pdf_name, but i realize that its a bit silly to have internal helpers to "avoid mistakes" that way)

**Comment by alexp1917** [comment]
re: the dependency, i think we shouldn't

**Comment by Lucas-C** [comment]
VICTORY! Acrobat Reader correctly displays alternate text!

2021-02-16 19_47_34-Window

This is ready for review 😊

@alexp1917 about your comment:
> is it possible to either make the `self.Type` follow an inheritance contract?

I'm sorry but I don't fully understand. Could elaborate on what kind of inheritance contract you are thinking about?

**Comment by alexp1917** [comment]
**case**
arguably, fpdf isn't very object oriented since its all in one class, but camel_case is observed there, so i think we shouldn't introduce that here (also isnt python more in favor of `self.alt_description` vs `self.ParentTree`, capitalization seems more like `C#` stuff).

Also, since we have the python type suggestions now, something i think is worthwhile is having a PdfName or `PDFName` type which is of course synonymous with strings, but provides clarity. The less PDF syntax we mix with python the better imo.

**type attr stuff**
as far as setting `self.Type = 'hardcoded'`, i was thinking it should be something like

```python
class SpecialType:
  type = "special"
  def __init__():
    pass
```

which is not exactly using inheritance, but it seems like it is more elegant to do it with the python lookup algorithm and not by overwriting the values set by the `super().__init__(**kwargs)` calls.

also this is probably good to have this be constant if its an attribute on a class, so maybe good application for setting [`__slots__`](https://book.pythontips.com/en/latest/__slots__magic.html) and making it readonly by not allocating space for it in the object itself (these are supposed to created in large numbers, potentially, as pages and images are added?)

<details>
<summary>
e.g.
</summary>

```diff
--- a/fpdf/structure_tree.py
+++ b/fpdf/structure_tree.py
@@ -134,13 +134,15 @@ class NumberTree(PDFObject):
 
 
 class StructTreeRoot(PDFObject):
+    # __slots__ = ["parent_tree", "k"] # are these not /also/ final
+    type = "/StructTreeRoot"
+
     def __init__(self, **kwargs):
         super().__init__(**kwargs)
-        self.Type = "/StructTreeRoot"
         # A number tree used in finding the structure elements to which content items belong:
-        self.ParentTree = NumberTree()
+        self.parent_tree = NumberTree()
         # The immediate child or children of the structure tree root in the structure hierarchy:
-        self.K = []
+        self.k = []
 
 
 class StructElem(PDFObject):
```
</details>

**PDFObject.serialize**
I dont very much enjoy that if elif stuff but i think the correct stopping point is 1) moving the list stuff into its own method so that it is at least flush with the others and 2) moving the control over what happens in the list-- conceptually-- into which ever class actually represents the list. it seems like it will bite later on if the "control" over the serialization of lists is determined in that class vs the others, but i dont have an answer for this one just yet.

im happy to go make some of these suggested changes if thats whats decided

also, is this supposed to be the basis for a future "compiler" layer as is sometimes the case, like is the `self.buffer = bytearray()` eventually going to be deprecated in favor of this? it seems like it almost makes sense, but not quite. so i think thats something that would be good to clarify. seems odd to develop this level of sophistication and only use it for a single feature. maybe there are benefits to dropping some of the `_out` and friends and re-implementing in the syntax tree and utils/syntax modules. not sure what this approach is capable of yet.

**Comment by alexp1917** [comment]
im just going to leave those code snippets up there for now and see if i still like them in a couple days

**Comment by Lucas-C** [comment]
Answering your comments:

> case
> arguably, fpdf isn't very object oriented since its all in one class, but camel_case is observed there, so i think we shouldn't introduce that here (also isnt python more in favor of self.alt_description vs self.ParentTree, capitalization seems more like C# stuff).

Alright, I'll drop the CamelCase-named attributes. I will have to introduce an extra function to perform the conversion though:
```python
def camel_case(property_name):
    return ''.join(x for x in property_name.title() if x != "_")
```

> Also, since we have the python type suggestions now, something i think is worthwhile is having a PdfName or PDFName type which is of course synonymous with strings, but provides clarity. The less PDF syntax we mix with python the better imo.

I dot not quite see the benefits of introducing such class in the context of this PR.
Could you elaborate a bit? Or maybe that could be part of another patch?

> type attr stuff
as far as setting self.Type = 'hardcoded', i was thinking it should be something like

> class SpecialType:
>   type = "special"
>   def __init__():
>     pass

The issue with this approach is that `type` won't be included when inspecting the `__dict__` of an instance of this class. Specifically in your example, `SpecialType().__dict__` is empty.
I added a comment in `PDFObject.serialize` to document & explain this.

> which is not exactly using inheritance, but it seems like it is more elegant to do it with the python lookup algorithm and not by overwriting the values set by the super().__init__(**kwargs) calls.

You may be misled there: the `super().__init__(**kwargs)` purpose is to all to pass the `n` property directly to the child classes constructors. I prefer this approach of using `**kwargs` over defining a `n` constructor argument in each child class because it makes separation of concerns slightly better (chaging the parent class construtor argument name won't require renamings in all child classes constructors), but I'd be happy to drop `**kwargs` usage if that makes the code clearer . What do you think?

> also this is probably good to have this be constant if its an attribute on a class, so maybe good application for setting __slots__ and making it readonly by not allocating space for it in the object itself (these are supposed to created in large numbers, potentially, as pages and images are added?)

Interesting, this is a very valid concern about limiting memory usage...
Sadly using `__slots__` would break the introspection mechanism I used based on `__dict__`. They are also not always very compatible with class inheritance.
My initial attempt at writing this class made use of `typing.NamedTuple` for all classes, with the same concern in mind of limiting memory usage. Overall it made the code less readable, as I needed several workarounds to have a mutable `ID` attribute in the `PDFObject` parent class. In the end I only used `NamedTuple` for the `MarkedContent` that is the most likely to be instantiated many times (one instance for every image having an alternate description). The same number of `StructElem` will be created during the lifetime of `StructureTreeBuilder`, so there may be another optimization to be done on this class. Other than that, the other classes are only instanciated once.

> `PDFObject.serialize`
> I dont very much enjoy that if elif stuff but i think the correct stopping point is 1) moving the list stuff into its own method so that it is at least flush with the others and 2) moving the control over what happens in the list-- conceptually-- into which ever class actually represents the list. it seems like it will bite later on if the "control" over the serialization of lists is determined in that class vs the others, but i dont have an answer for this one just yet.

OK, I'll try to see what I can do about this.

> also, is this supposed to be the basis for a future "compiler" layer as is sometimes the case, like is the self.buffer = bytearray() eventually going to be deprecated in favor of this? it seems like it almost makes sense, but not quite. so i think thats something that would be good to clarify. seems odd to develop this level of sophistication and only use it for a single feature. maybe there are benefits to dropping some of the _out and friends and re-implementing in the syntax tree and utils/syntax modules. not sure what this approach is capable of yet.

No, this module only aims to build a _Structure Tree_, which is a hierarchical structure describe in the PDF spec that lives **in parallel** of the pages hierarchy and strem contents. It **cannot** replace them.
This _Structure Tree_ may have other uses than providing alternate descriptions to images (like alt text on links or providing a document table of contents), but it won't replace `FPDF.buffer` & `FPDF._out`

**Comment by Lucas-C** [comment]
@alexp1917 I added a commit that improved things a bit.

Please tell me what you think of the latest version of the code when you have some time 😉

**Comment by alexp1917** [comment]
lgtm!

**Comment by alexp1917** [comment]
@Lucas-C this part is referring to my snippet where I tried to work around the issue you describe:

> overwriting the values set by the super

(the last snippet in my feedback above.) it seems explicit enough now, especially with all the discussion in this pr.

**Pull request merged**
