### PR TITLE
Implementing document outline & table of contents

### PR DESCRIPTION
**Pull request by Lucas-C**

### CODE REVIEW

**Comment by Lucas-C** [comment]
This is ready for review!

2 new PDF test samples have been added illustrating the kind of outline & table of contents that can be generated:
https://github.com/PyFPDF/fpdf2/tree/doc-outline-and-toc/test/outline

**Comment by Lucas-C** [comment]
Code can be reviewed but I need to finish one last thing before merging: redact the new documentation page.

**Comment by Lucas-C** [comment]
Documentation page has been redacted.

Preview using GitHub markdown viewer: https://github.com/PyFPDF/fpdf2/blob/doc-outline-and-toc/docs/DocumentOutlineAndTableOfContents.md

**Comment by Lucas-C** [comment]
@alexp1917 Do you think you will have time to review this PR in the following days?

Anyone else interested in providing feeback on this is welcome!

**Comment by alexp1917** [comment]
looking at this now

**Review by alexp1917 — APPROVED** [review]
looks like some parts of the code will need to be revisited in tests, but a good chunk of this is just moving code around, which, alright fine. since this is right before a release, and i remember that we have a different procedure for updating it in all the places that I haven't done yet, we can just do the release to close #133  and maybe yank it later if anything. I would release the version before merging and then merge, and then release a `rc` or something like that. feel free to proceed as normal if you're confident in this one (#130). I am assuming that the main reason for releasing 2.3.3 is some other changes. if we are releasing 2.3.3 for the TOC stuff then just release as 2.3.3 and yank if necessary. feel free to do as you feel best, i am not as familiar with this project as I'm being pulled in many other directions lately.

**Comment by Lucas-C** [comment]
OK, thank you @alexp1917.
I'll go with merging & releasing this then.

**Pull request merged**
