### PR TITLE
Added empty method  to class fpdf.

### PR DESCRIPTION
**Pull request by jeettrivedi**
Draft PR to work on #496.

e.g. Fixes #0 

**Checklist**:

- [ ] The GitHub pipeline is OK (green), 
      meaning that both `pylint` (static code analyzer) and `black` (code formatter) are happy with the changes of this PR.

- [ ] A unit test is covering the code added / modified by this PR

- [ ] This PR is ready to be merged 

- [ ] In case of a new feature, docstrings have been added, with also some documentation in the `docs/` folder

- [ ] A mention of the change is present in `CHANGELOG.md`

By submitting this pull request, I confirm that my contribution is made under the terms of the [GNU LGPL 3.0 license](https://github.com/PyFPDF/fpdf2/blob/master/LICENSE).

### CODE REVIEW

**Comment by Lucas-C** [comment]
That's a good start! :)

**Comment by Lucas-C** [comment]
Hi @jeettrivedi

Are you still planning to work on this, or should I close this PR for now?

**Comment by jeettrivedi** [comment]
> Hi @jeettrivedi
> 
> Are you still planning to work on this, or should I close this PR for now?

Hey @Lucas-C, I am still working on it. I haven't had the chance to review the link you provided but I am hoping to this weekend.

**Comment by Lucas-C** [comment]
Hi @jeettrivedi!

Just a heads up on this PR: are you still planning to work on it?
It's totally fine if you don't have the time or motivation anymore, but please keep us informed 😊

**Pull request closed without merging**
