### PR TITLE
New optional `font_cache_dir` optional argument of the `fpdf.FPDF` constructor

### PR DESCRIPTION
**Pull request by Lucas-C**

### CODE REVIEW

**Comment by alexanderankin** [comment]
as ive mentioned in #101 i dont think getting rid of this cache is correct - deprecating and leaving a ton of warnings is good, but should retain backwards compatibility. (minimal code change for migrating users is ideal)

**Comment by Lucas-C** [comment]
The cache is enabled by default and will stay, it's just cache mode 2 that this PR aims to get rid of 😊

**Comment by alexanderankin** [comment]
@Lucas-C do you mind sending me an email to `alexanderankin@gmail.com`? thanks.

**Comment by Lucas-C** [comment]
@alexp1917 Do you think we should preserve the `FPDF_CACHE_DIR` module variable?
I'd prefer to transform it into an attribute of the `FPDF` class, but it's true that users code previously relying on setting `fpdf.FPDF_CACHE_DIR` would break...

On the other hand, the current behaviour is really error-prone:
```python
from fpdf import fpdf
fpdf.FPDF_CACHE_DIR = 1  # OK

import fpdf
fpdf.FPDF_CACHE_DIR = 1  # KO: does nothing but does not raise an error
```
Hence I think it's worth revising how this control setting can be configured, but I'd like your opinion 😊

**Comment by Xtrem532** [comment]
I would recommend to remove the module variable and add a module-level `__getatter__` to both `fpdf` and `fpdf.fpdf` that raises an Error if someone tries to access `"FPDF_CACHE_DIR"`. That can be used for all module level variables, as those are a huge error source for people migrating from PyFPDF1.

(I know I have seen something like this used in the build-in libs to throw `DeprecationWarning` somewhere, but I don't remember where)

**Comment by alexp1917** [comment]
I unfortunately havent had time to work on this but that seems possible and
correct.

**Comment by Lucas-C** [comment]
I added a commit adding DeprecationWarnings.

However, an `AttributeError` is still raised.

Any feedback on this solution is welcome

**Comment by alexp1917** [comment]
@Lucas-C how about these changes, which ive pushed to `font_cache_dir_tmp` (feel free to pull those however is most convenient)

After all, we want to warn people not ruin their day.

<details>
<summary>diff</summary>

```diff
diff --git a/fpdf/util/deprecation.py b/fpdf/util/deprecation.py
index 2a0b2a2..1a5b638 100644
--- a/fpdf/util/deprecation.py
+++ b/fpdf/util/deprecation.py
@@ -12,7 +12,7 @@ class WarnOnDeprecatedModuleAttributes(ModuleType):
                 DeprecationWarning,
                 stacklevel=2,
             )
-            raise AttributeError(f"module {self.__name__} has no attribute {name}")
+            return None
         # pylint: disable=no-member
         return super().__getattr__(self, name)
 
@@ -25,5 +25,5 @@ class WarnOnDeprecatedModuleAttributes(ModuleType):
                 DeprecationWarning,
                 stacklevel=2,
             )
-            raise AttributeError(f"module {self.__name__} has no attribute {name}")
+            return
         return super().__setattr__(self, name, value)
diff --git a/test/fonts/test_add_font.py b/test/fonts/test_add_font.py
index 1bc7c19..053b20d 100644
--- a/test/fonts/test_add_font.py
+++ b/test/fonts/test_add_font.py
@@ -30,24 +30,24 @@ def test_deprecation_warning_for_FPDF_CACHE_DIR():
     # pylint: disable=import-outside-toplevel,pointless-statement,reimported
     from fpdf import fpdf
 
-    with pytest.warns(DeprecationWarning), pytest.raises(AttributeError):
+    with pytest.warns(DeprecationWarning):
         fpdf.FPDF_CACHE_DIR
-    with pytest.warns(DeprecationWarning), pytest.raises(AttributeError):
+    with pytest.warns(DeprecationWarning):
         fpdf.FPDF_CACHE_DIR = "/tmp"
-    with pytest.warns(DeprecationWarning), pytest.raises(AttributeError):
+    with pytest.warns(DeprecationWarning):
         fpdf.FPDF_CACHE_MODE
-    with pytest.warns(DeprecationWarning), pytest.raises(AttributeError):
+    with pytest.warns(DeprecationWarning):
         fpdf.FPDF_CACHE_MODE = 1
 
     import fpdf
 
-    with pytest.warns(DeprecationWarning), pytest.raises(AttributeError):
+    with pytest.warns(DeprecationWarning):
         fpdf.FPDF_CACHE_DIR
-    with pytest.warns(DeprecationWarning), pytest.raises(AttributeError):
+    with pytest.warns(DeprecationWarning):
         fpdf.FPDF_CACHE_DIR = "/tmp"
-    with pytest.warns(DeprecationWarning), pytest.raises(AttributeError):
+    with pytest.warns(DeprecationWarning):
         fpdf.FPDF_CACHE_MODE
-    with pytest.warns(DeprecationWarning), pytest.raises(AttributeError):
+    with pytest.warns(DeprecationWarning):
         fpdf.FPDF_CACHE_MODE = 1
```

</details>

**Comment by alexp1917** [comment]
overall, simplifying to just get rid of the hash is definitely the way to go, im still mixed on the deprecation but i also dont know that i love global config vars like that. so I've looked through this, I would like to not crash the program for folks who are coming from the other edition of this python library, and this is good to go.

**Comment by Lucas-C** [comment]
Yeah, I wondered too if an exception should be raised or not...

Thanks for the feedback @alexp1917
I'll follow your advice.
Now merging your branch: https://github.com/PyFPDF/fpdf2/pull/106

**Pull request merged**
