### PR TITLE
Added Encryption Functionality

### PR DESCRIPTION
**Pull request by Brianrmendes**

### CODE REVIEW

**Comment by Lucas-C** [comment]
Thanks for the PR @Brianrmendes!

I'd prefer not to add a dependency on `PyPDF2` though.

However feel free to include in a PR a documentation update with a new page describing
 how to use both libraries to produce encrypted PDFs!

Similar to what was already done here:
* https://pyfpdf.github.io/fpdf2/Metadata.html
* https://pyfpdf.github.io/fpdf2/Barcodes.html#pdf-417
* https://pyfpdf.github.io/fpdf2/ExistingPDFs.html

**Review by alexp1917 — CHANGES_REQUESTED** [review]
This test does not conform to the testing framework we use. you can look at the Github Actions CI that we are running to see how to run the tests, basically just `pytest test/your_test_file.py` and copy the format of the existing tests.

The implementation as it stands does not conform to the pattern of [fpdf usage][1], which is basically creating an object, calling some methods, and producing a file as an output (or an http response). It operates on input from the command line as opposed to the contents of the document (text, images, shapes which are added by other method calls).

Lastly, the fpdf library which this one is based on is intended for use in server side web applications, and while this one is more general, we dont want to limit its usage to interactive command line applications. so for that reason its unlikely that code containing calls to the `input` function would be merged into the library.

[1]: http://www.fpdf.org/en/tutorial/tuto1.htm

**Review by pandrey2003 — COMMENTED** [review]
Sorry to chip in, but what about re-considering such points:

- extra dependencies should be added with caution;
- we might want to re-read the initial [issue](https://github.com/PyFPDF/fpdf2/issues/194). Lucas suggests adding an extra parameter to the `output` method, which might be better designed than adding an extra `encryption` method;
- tests might be designed to compare received and expected values (how they [are](https://github.com/pikepdf/pikepdf/blob/master/tests/test_encrypt.py) for `pikepdf`);
- commented code might look a bit obscure for a developer;
- checking changes with the linter would assure the same code style amid the project.

Anyway, these are just my opinionated ideas of the library user, and I can be absolutely wrong.

**Comment by alexp1917** [comment]
thanks @pandrey2003 - agree with all points except the commented code - pull requests with large sections of commented code should not be merged at all - either the commented code is removed or the comments reworded to explain what was removed. if the code is really necessary it should be uncommented.

Sorry for my lack of involvement on this pr and issue but to me, it seems that the requirements are clear - change the normal workflow so that a pdf can be output to a file but with encryption. this pr attempts to circumvent most of the code paths of this library and simply combine encryption functionality with the rest of the fpdf2 package.

**Comment by Lucas-C** [comment]
Closing this for now

Discussion can continue on #194

**Pull request closed without merging**
