### PR TITLE
circle method added to FPDF class

### PR DESCRIPTION
**Pull request by mjbeam64**
I saw this request (Add a FPDF.circle method #59) here: https://github.com/PyFPDF/fpdf2/issues/59

### CODE REVIEW

**Comment by Lucas-C** [comment]
You removed `fpdf/fpdf.py ` in your latest commit!

Otherwise, thanks for contributing.
Could you please also add unit test as part of this PR?

**Review by Lucas-C — CHANGES_REQUESTED** [review]
You removed fpdf/fpdf.py in your latest commit!

Otherwise, thanks for contributing.
Could you please also add unit test as part of this PR?

**Comment by Lucas-C** [comment]
Sorry @mjbeam64, without an answer on your part I think I'll close this PR soon...

**Comment by mjbeam64** [comment]
Hello Lucas. Sorry for not responding earlier. I have no idea how to add a unit test. Please delete the pull request. Thanks...Mike

**Pull request closed without merging**
