### PR TITLE
New optional 'x' parameter for FPDF.set_link - close #178

### LINKED ISSUE #178: Feature Request: set_link x arg
Hello,

Currently consider fpdf2 best pdf creator for my needs and plan to use it for generating technical drawing packages.
Each technical page is a high res image with a device rectangle on top with additional data. 
Those package contains a large amount of pages with hundreds of devices, an fast and easy navigation is therefor crucial.

Is it possible to add a 'x' argument to set_link?
That makes it possible, combined with zoom, to jump and focus on an specific part of a page, in my case containing a device but I can come up with more use cases.

### PR DESCRIPTION
**Pull request by Lucas-C**
_cf._ #178

### CODE REVIEW

**Comment by mrEscen** [comment]
Hello

Thanks Lucas for your fast implementation.
Did some testing by placing a rectangles and linking to this rectangle coordinates.
If everything works correctly this rectangles should appear in the left top corner, like shown in the image.
image


I have to multiply with pdf.k to achieve this, could this be correct?
`return f"[{page} /XYZ {self.x * pdf.k} {top:.2f} {self.zoom}]"`

**Comment by Lucas-C** [comment]
Well spotted!

I fixed the PR accordingly.
Could you check that it works fine now with your test case?

**Comment by mrEscen** [comment]
Fix is working correctly in my test case.
Thanks

**Comment by Lucas-C** [comment]
Thanks @mrEscen!
Merged

**Pull request merged**
