### PR TITLE
[Added] Doc on generating Code128 Barcode

### LINKED ISSUE #720: Doc: provide an usage example of combining fpdf2 with python-barcode
We already have a page about [Barcodes](https://pyfpdf.github.io/fpdf2/Barcodes.html) in our documentation.
It was recently reported that we don't support code 128 barcodes: https://github.com/PyFPDF/fpdf2/discussions/719

[python-barcode](https://python-barcode.readthedocs.io/en/stable/) seems like a great library that can produces images for many barcode formats, using Pillow.

It would be interesting to provide a documentation section on how to generate barcodes with `python-barcode` and embed them in PDFs using `fpdf2`. Priority should be given to documenting how to insert them as SVG, as it will produce smaller PDF documents thant embedding barcodes as rater images.

---

By implementing this feature you, as a benevolent [FLOSS](https://en.wikipedia.org/wiki/Free/libre_and_open-source_software) developper, will provide access to the large community of fpdf2 users to a useful PDF functionality.
As a contributor you will get review feedbacks from maintainers & other contributors, and learn about the lifecycle & structure of a Python library on the way.
You will also be added into the [contributors list & map](https://github.com/PyFPDF/fpdf2#contributors-).

This issue can count as part of [hacktoberfest](https://hacktoberfest.com)

### PR DESCRIPTION
**Pull request by ssavi-ict**
- Fixes #720
- Added Code128 Barcode documentation.

**Checklist**:

- [ ] The GitHub pipeline is OK (green), 
      meaning that both `pylint` (static code analyzer) and `black` (code formatter) are happy with the changes of this PR.

- [ ] A unit test is covering the code added / modified by this PR

- [ ] This PR is ready to be merged 

- [ ] In case of a new feature, docstrings have been added, with also some documentation in the `docs/` folder

- [ ] A mention of the change is present in `CHANGELOG.md`

By submitting this pull request, I confirm that my contribution is made under the terms of the [GNU LGPL 3.0 license](https://github.com/PyFPDF/fpdf2/blob/master/LICENSE).

### CODE REVIEW

**Comment by ssavi-ict** [comment]
@Lucas-C, Please have a look at this PR. And let me know of any further issues. 

Thank You.

**Review by Lucas-C — APPROVED** [review]

**Comment by Lucas-C** [comment]
This is perfect!
Thank you @ssavi-ict 😊
Merging now

**Comment by Lucas-C** [comment]
@allcontributors please add @ssavi-ict for documentation

**Comment by Lucas-C** [comment]
Congratulations, it's published in `fpdf2` documentation! 😊
https://pyfpdf.github.io/fpdf2/Barcodes.html#code128

**Pull request merged**
