### PR TITLE
Add support to "line-height" tag in html

### LINKED ISSUE #622: Add html <line-height> tag support
**Please explain your intent**
The html to pdf functionality lacks support of line-height adjusting.

**Describe the solution you'd like**
I have read some parts of the documentation, but fails to find any reference to line height settings. Maybe there is one, but I didn't found it. 
Setting default line height while `setfont()` is also desired, though I consider it harder to implement.

**Additional context**
I'm willing to launch a PR to this issue. Let me know what think about this feature!

### PR DESCRIPTION
**Pull request by Bubbu0129**
e.g. Fixes #622 

**Checklist**:

- [ ] The GitHub pipeline is OK (green), 
      meaning that both `pylint` (static code analyzer) and `black` (code formatter) are happy with the changes of this PR.

- [ ] A unit test is covering the code added / modified by this PR

- [ ] This PR is ready to be merged 

- [ ] In case of a new feature, docstrings have been added, with also some documentation in the `docs/` folder

- [ ] A mention of the change is present in `CHANGELOG.md`

After checking some code, I found that `self.h` is only defined in `self.set_font`. So I defined two variables `self.line_height` and `self.font_height`. 
`self.line_height` keeps track of the line height setting so that another `self.set_font`, for instance `<font>` in `<p line-height=?>`, won't drop the line height value. 
`self.font_height` is a backup to redeem `self.h` after the endtag.

However, `line-height` in html can be set unitlessly, in length, in percentage or by keywords. I only solved the unitless case. 

By submitting this pull request, I confirm that my contribution is made under the terms of the [GNU LGPL 3.0 license](https://github.com/PyFPDF/fpdf2/blob/master/LICENSE).

### CODE REVIEW

**Comment by Lucas-C** [comment]
Thank you for the PR!
Could you please provide a new unit test?
In https://github.com/PyFPDF/fpdf2/blob/master/test/html/test_html.py

You can find ome guidance on how to create them here:
https://pyfpdf.github.io/fpdf2/Development.html#assert_pdf_equal-writing-new-tests

**Comment by Lucas-C** [comment]
@allcontributors please add @Bubbu0129 for code

**Comment by Bubbu0129** [comment]
Why isn't codecov check successful? Is the code wrong or what?

**Comment by Lucas-C** [comment]
> Why isn't codecov check successful? Is the code wrong or what?

As I really mentioned in my previous comment, a unit covering this ne feature will be required.
Adding it should also please CodeCov.

Also, could you add mention of this change in `ChANGELOG.md` as part of this PR, please?

**Comment by Bubbu0129** [comment]
Ok, I’m gonna write it asap. Covid strikes hard, so you may need to wait a couple of days.

On Dec 14, 2022, at 7:08 PM, Lucas Cimon ***@***.***> wrote:

﻿

Why isn't codecov check successful? Is the code wrong or what?

As I really mentioned in my previous comment, a unit covering this ne feature will be required.
Adding it should also please CodeCov.

Also, could you add mention of this change in ChANGELOG.md as part of this PR, please?

**Comment by Lucas-C** [comment]
> Ok, I’m gonna write it asap. Covid strikes hard, so you may need to wait a couple of days.

No worries. Take care

**Comment by Bubbu0129** [comment]
This PR is forced to close after my wrong operation. It cannot be reopened, at least be myself. I launched a new one.

**Pull request closed without merging**
