### PR TITLE
adding Bengali tutorial

### PR DESCRIPTION
**Pull request by ssavi-ict**
#267 Added Bengali Tutorial 

**Checklist**:

- [x] The GitHub pipeline is OK (green), 
      meaning that both `pylint` (static code analyzer) and `black` (code formatter) are happy with the changes of this PR.

- [x] A unit test is covering the code added / modified by this PR

- [x] This PR is ready to be merged 

- [ ] In case of a new feature, docstrings have been added, with also some documentation in the `docs/` folder

- [x] A mention of the change is present in `CHANGELOG.md`

By submitting this pull request, I confirm that my contribution is made under the terms of the [GNU LGPL 3.0 license](https://github.com/PyFPDF/fpdf2/blob/master/LICENSE).

### CODE REVIEW

**Comment by ssavi-ict** [comment]
@Lucas-C added Bengali Tutorial. 
I have added the information in `index.md`. 
Do I need to add any information in `CHANGELOG.md` and `README.md` ?

**Comment by Lucas-C** [comment]
Thank you for making this translation @ssavi-ict!

Could you please also add a link in `README.md` and a mention of this change in `CHANGELOG.md`?

**Comment by ssavi-ict** [comment]
@Lucas-C updated `CHANGELOG` and `INDEX`. Please have a look.

**Comment by ssavi-ict** [comment]
Hello, @Lucas-C . Please let me know if there is any issue with this PR. I did not get any ack yet.

**Comment by Lucas-C** [comment]
Hi @ssavi-ict!

You PR is excellent, thank you for submitting it 😊

The reason why I haven't merged it yet is that I am currently working on a big PR: https://github.com/PyFPDF/fpdf2/pull/703
This PR will introduce a new `table()` method, and hence the section 5 of the tutorial will change a lot:
https://github.com/PyFPDF/fpdf2/blob/table/docs/Tutorial.md#tuto-5---creating-tables

Would you be OK to adapt your PR in order to use the new version of this section 5, from the English tutorial?

**Comment by ssavi-ict** [comment]
@Lucas-C , I would love to. Please notify me in this issue #267 **Section 5** English tutorial is ready. I will move to make a translation of Section 5

**Comment by shindodkar** [comment]
Hi, @ssavi-ict I am new to open source project . So, will you guide me on this project.

**Comment by Lucas-C** [comment]
Hi @ssavi-ict!

Just a heads-up: PR #703 has been merged 😊

**Comment by ssavi-ict** [comment]
@Lucas-C Thanks for notifying me. Will start working on it soon.

**Comment by ssavi-ict** [comment]
@Lucas-C Could you please check the current PR? Updated with recent Tutorial changes.

**Pull request closed without merging**
