### PR TITLE
doc: add Russian tutorial

### PR DESCRIPTION
**Pull request by AABur**
#267 translate the one-page tutorial into Russian!

### CODE REVIEW

**Review by Lucas-C — APPROVED** [review]
Perfect, thank you!

**Comment by AABur** [comment]
@Lucas-C Super!
Not that it matters much, but it will be nice to see myself on the list of contributors.

**Comment by Lucas-C** [comment]
Of course:

@allcontributors please add @AABur for translation

**Comment by Lucas-C** [comment]
FYI I mentioned you in this blog article 😉
https://chezsoi.org/lucas/blog/hacktoberfest-on-fpdf2.html

**Pull request merged**
