### PR TITLE
Allowing to use a subclass of HTML2FPDF by setting FPDF.HTML2FPDF_CLASS

### PR DESCRIPTION
**Pull request by Lucas-C**
_cf._ https://github.com/PyFPDF/fpdf2/issues/223

### CODE REVIEW

**Comment by ping** [comment]
Found an issue using the exact sample code provided. The pdf TOC generated skips Level 1.

CustomHTML2FPDF

**Comment by ping** [comment]
I tested a little more with different headings. The results are annotated below:

```python
from fpdf import FPDF, HTMLMixin, HTML2FPDF


class CustomHTML2FPDF(HTML2FPDF):
    def render_toc(self, pdf, outline):
        pdf.cell(txt='Table of contents:', ln=1)
        for section in outline:
            pdf.cell(txt=f'* {section.name} (page {section.page_number})', ln=1)


class PDF(FPDF, HTMLMixin):
    HTML2FPDF_CLASS = CustomHTML2FPDF


test_contents = [
    # Original sample code
    # pdf toc: Level 1 is skipped
    """<toc></toc>
<h1>Level 1</h1>
<h2>Level 2</h2>
<h3>Level 3</h3>
<h4>Level 4</h4>
<h5>Level 5</h5>
<h6>Level 6</h6>
<p>paragraph<p>""",
    # pdf toc: all levels are generated
    """<toc></toc>
<h1>Level 1</h1>
<h2>Level 2</h2>
<h1>Level 1A</h1>
<h2>Level 2A</h2>
<p>paragraph<p>""",
    # pdf toc: only Level 3 is generated
    """<toc></toc>
<h2>Level 2</h2>
<h3>Level 3</h3>
<h1>Level 1A</h1>
<h2>Level 2A</h2>
<h3>Level 3A</h3>
<p>paragraph<p>""",
    # pdf toc: Level 1 is skipped
    """<toc></toc>
<h1>Level 1</h1>
<h2>Level 2</h2>
<h2>Level 2A</h2>
<h3>Level 3A</h3>
<p>paragraph<p>""",
]

for i, content in enumerate(test_contents, start=1):
    pdf = PDF()
    pdf.add_page()
    pdf.write_html(content)
    pdf.output(f"html_toc_{i}.pdf")
```

**Comment by Lucas-C** [comment]
Could this be dependent on your PDF reader ?

I do not see any issue using Sumatra:
2021-09-30 06_15_37-Steam

**Comment by ping** [comment]
Interesting. I'm using the default macos Preview viewer. I dragged the file into Firefox and was able to see the outlines like you did. I guess my issue is due to a problem with the macos viewer.

**Comment by Lucas-C** [comment]
Mergin this then

Thanks for the feedback @ping!

**Pull request merged**
