### PR TITLE
Add support to "line-height" tag in write_html()

### LINKED ISSUE #622: Add html <line-height> tag support
**Please explain your intent**
The html to pdf functionality lacks support of line-height adjusting.

**Describe the solution you'd like**
I have read some parts of the documentation, but fails to find any reference to line height settings. Maybe there is one, but I didn't found it. 
Setting default line height while `setfont()` is also desired, though I consider it harder to implement.

**Additional context**
I'm willing to launch a PR to this issue. Let me know what think about this feature!

### PR DESCRIPTION
**Pull request by Bubbu0129**
Fixes #622 

**Checklist**:

- [x] The GitHub pipeline is OK (green), 
      meaning that both `pylint` (static code analyzer) and `black` (code formatter) are happy with the changes of this PR.

- [x] A unit test is covering the code added / modified by this PR

- [x] This PR is ready to be merged 

- [x] In case of a new feature, docstrings have been added, with also some documentation in the `docs/` folder

- [x] A mention of the change is present in `CHANGELOG.md`

PS: Changing of `html_features.pdf` is due to the ruduction of line height with the reduction of font size, so there is a minor difference.

By submitting this pull request, I confirm that my contribution is made under the terms of the [GNU LGPL 3.0 license](https://github.com/PyFPDF/fpdf2/blob/master/LICENSE).

### CODE REVIEW

**Review by Lucas-C — CHANGES_REQUESTED** [review]
Note: this is a follow-up of #624

Thank you for adding a unit test!
This PR looks promising 😊 Thank you for contributing.
I gave you some feedback.

As you can see in the GitHub Actions logs, `pylint` is unhappy with the very long line length in the unit test added:
```
$ pylint fpdf test tutorial/tuto*.py
************* Module test.html.test_html
test/html/test_html.py:611:0: C0301: Line too long (657/150) (line-too-long)
test/html/test_html.py:612:0: C0301: Line too long (642/150) (line-too-long)
test/html/test_html.py:613:0: C0301: Line too long (661/150) (line-too-long)
test/html/test_html.py:614:0: C0301: Line too long (629/150) (line-too-long)
```
Could you please shorten those lines?

**Comment by Bubbu0129** [comment]
I defined two attributes, `self.font_height` and `self.line_height`.
`self.font_height` keeps track of the original line height decided by the font size, I think it is needed.
`self.line_height` records the unitless line height. If the font size is altered, as long as `self.line_height` remains the same, the actual line height can stretch accordingly. Test file [html_custom_line_height.pdf](https://github.com/Bubbu0129/fpdf2/blob/master/test/html/html_custom_line_height.pdf) is an example.

**Review by Lucas-C — APPROVED** [review]

**Comment by Lucas-C** [comment]
Sorry, `pylint` is being excessively strict, there is one missing newline:
```
pylint fpdf test tutorial/tuto*.py
************* Module fpdf.html
fpdf/html.py:864:0: C0305: Trailing newlines (trailing-newlines)
```

I think that after this is solved I'm going to merge this.

**Comment by Bubbu0129** [comment]
I think its good now.

**Comment by Lucas-C** [comment]
Perfect!
Thank you for your work on this @Bubbu0129 😊
Nice contribution!
Merging now

**Pull request merged**
